# In this notebook we will cover the most important concepts of Tensorflow
especially
* intro of tensor
* getitng info from tensor
* manipulating tensors
* tensors and Numpy
* using @tf.function (a way to speed up python functions)
* using GPUs or TPUs on tensorflow
* Excercise to try

# Introdcutions to tensors

In [1]:
# impoort tensorflwow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimensions of a tensor (ndim: number of dimensiosn)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,6])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  6], dtype=int32)>

In [5]:
# Check the dimension of the vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the dimension of the matrix
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[1.,2.],
                [3.,4.],
                [5.,6.]], dtype = tf.float16)  # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [9]:
# What is the number of dimension of another_matrix?
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
            [4,5,6]],
            [[7,8,9],
            [10,11,12]],
            [[13,14,15],
            [16,17,18]]
            ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
another_tensor = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
another_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [13]:
another_tensor.ndim
# The .ndim attribute simply returns the length of the shape tuple. Since the tuple (3, 3) has two elements, ndim is 2
# A tensor's dimension refers to its number of axes. It's also commonly called the tensor's rank or order. It defines the structure of the data by specifying how many indices are required to locate a single element within the tensor.
# Think of the dimension as the level of nesting in the tensor's data structure.

2

#### What we have created so far
 * scalar: a single number
 * vector: a number with direction
 * matrix: a 2-dimensional array of numbers
 * tensor: a n-dimensional array of numbers (n can be any number, n=0 a scalar, n=1 a vector)

 * A tensor's dimension refers to its number of axes. It's also commonly called the tensor's rank or order. It defines the structure of the data by specifying how many indices are required to locate a single element within the tensor.
 * Think of the dimension as the level of nesting in the tensor's data structure.

### Creating tensors with tf.Variable

In [14]:
# Create a tensor with tf.Variable() as above
changible_tensor = tf.Variable([10,7])
unchangible_tensor = tf.constant([10,7])
changible_tensor, unchangible_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Lets change one element in our changible_tensor
# changible_tensor[0] = 7
# changible_tensor
# 'ResourceVariable' object does not support item assignment

In [16]:
# How about we try .assign()
changible_tensor[0].assign(7)
changible_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# Let's try change our unchangible tensor
# unchangible_tensor[0].assign(7)
# unchangible_tensor
# 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

**Note:**
Rarely in practiwce we will need to decide whether to use tf.constant() or tf.Variable(), as Tensorflow does it for you, if in doubt, use tf.constant and later change it if needed

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers

In [18]:
# Create two random (but the same) tensors

In [19]:
random_1 = tf.random.Generator.from_seed(42)   # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

# Are they equal? => equal because of the same seed
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [20]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
               [3,4],
               [2,5]])
not_shuffled.ndim, not_shuffled

# Shuffle our non_shuffled tensor
tf.random.set_seed(42)               # global level random seed
tf.random.shuffle(not_shuffled, seed = 42)   # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

useful link:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [21]:
# Practive: write a random tensor and shuffle it
random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape = (2,2))

# If global seed is set, then the seed is used
tf.random.set_seed(42)                            # global level random seed
random_tensor_1_shuffled = tf.random.shuffle(random_tensor_1,seed=42)    # operational level random seed
random_tensor_1, random_tensor_1_shuffled

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.07595026, -1.2573844 ],
        [-0.7565803 , -0.06854702]], dtype=float32)>)

In [22]:
random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape = (2,2))

# If global seed is not set, then the seed is not used even the local seed is set
random_tensor_2_shuffled = tf.random.shuffle(random_tensor_2, seed = 42)
random_tensor_2, random_tensor_2_shuffled

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]], dtype=float32)>)

* The reason to use tf.random.shuffle method is to ensure the randomness at the input layer
* If we want our shuffled tensor to be in the same order, we need to use the global level random seed as well as the operational level random seeed, (If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.) since the neutal network initilize itself with random patterns, we need to use operational level random seed to ensure the outcome is reproducible


### Other way to make tensors

In [23]:
# Create a tensor of all 1's
tf.ones(shape=(10,7))  # shape(a,b,c) a: number of outer-most layer, b:next layer, c: inner-most layer

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Create a tensor of all 0's
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [25]:
# We can also turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)  # create a numpy array bewtween 1 and 25
numpy_A

# X = tf.constant(some_matrix), "X" capital for matrix or tensor
# y = tf.constant(vector), "y" non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

The numpy.arange() function is a core function within the NumPy library in Python, used for creating arrays with evenly spaced values within a defined interval, numpy.arange([start, ]stop, [step, ]dtype=None)

start
(optional): The beginning of the interval (inclusive). Defaults to 0 if not provided.
stop:
The end of the interval (exclusive). The generated array will contain values up to, but not including, this value.
step
(optional): The spacing between values. Defaults to 1 if not provided. Can be negative for descending sequences.


In [26]:
# Convert a numpy array to a tensor "A"
A = tf.constant(numpy_A)             # without modified shape
B = tf.constant(numpy_A, shape = (2,3,4))   # with modified shape
C = tf.constant(numpy_A, shape = (3,8))
A, B, C

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [27]:
# Checking number of dimensions
A.ndim, B.ndim, C.ndim

(1, 3, 2)

The difference between tensor and a numpy array is that tensor can be run on a GPU while storing the same information as array

### Getting information form tensors
When dealing with tensor, we probably want to be aware of the following attributes:
* Shape - tensor.shape
* Rank - tensor.ndim
* Axes or dimension - tensor[0], tensor[ :1]
* Size - tf.size(tensor)

In [28]:
# create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [31]:
2 * 3 * 4 * 5

120

In [32]:
# Get various attribute of the tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimension (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Element along 0-axis:", rank_4_tensor.shape[0])
print("Element along the last axis:", rank_4_tensor.shape[-1])
print("Total number of element in the tensor:", tf.size(rank_4_tensor))
print("Total number of element in the tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimension (rank): 4
Shape of tensor: (2, 3, 4, 5)
Element along 0-axis: 2
Element along the last axis: 5
Total number of element in the tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of element in the tensor: 120


### Indexing tensors
Tensors can be indexed just like python list
* The main difference is that TensorFlow supports true multi-axis slicing in a single expression, which standard Python lists do not.


* Foe example, the slicing syntax [dim1, dim2, dim3, dim4] is used to access elements in a 4D tensor. (sliciing is performed on each dimension)

* While the basic slicing concept is shared, TensorFlow's slicing is built for high-performance, multi-dimensional data manipulation and is far more capable than Python's native list slicing.

In [33]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [34]:
# Get the first 2 elements of each dimensions
rank_4_tensor[0]
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
# Get the first element of each dimension form each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
# lets try another
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [37]:
mytensor = tf.constant([
            [[1,2,3],
            [4,5,6],
            [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]
                ])

mytensor[0:2,:,:], mytensor[0:2,0:2,:], mytensor[0:2, 0:2, 0:2]

(<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[10, 11, 12],
         [13, 14, 15]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 4,  5]],
 
        [[10, 11],
         [13, 14]]], dtype=int32)>)

In [38]:
some_list = [1,2,3,4]
some_list[-1]

4

In [39]:
# Create a rank-2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
               [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [40]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [41]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]    # same as rank_2_tensor[:,:,tf.newaxix]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
# Alternative to tf.newaxix
tf.expand_dims(rank_2_tensor, axis=-1)    # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

 In TensorFlow, an axis refers to a specific dimension of a tensor. You can think of it as an index that specifies which dimension of the tensor you want to operate on. The axes are numbered starting from 0.

tf.expand_dims(): https://www.tensorflow.org/api_docs/python/tf/expand_dims

In [43]:
tf.expand_dims(rank_2_tensor, axis = 0)   # expand the 0--axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [44]:
tf.expand_dims(rank_2_tensor, axis = 1)   # expand the 1--axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

When expanding a tensor, the original number in the tensor remains the same while the dimension changed

### Manipulatifng tensors (tensor operations)

**Basic operations**

'+', '-', '*', '/'

In [45]:
# Yoou can add value to a tensor using addition oeprator
tensor = tf.constant([[10,7], [3,4]])
tensor+10

# [[10, 7], [3, 4]] + 10 is treated as: [[10, 7], [3, 4]] + [[10, 10], [10, 10]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [46]:
# original tensor is unchanged after addition
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [47]:
# unless we reset it
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [48]:
# Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [49]:
# subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
# We can use the tensorflow's built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

If we want the temsor operation to be fast (run on GPU), then we need to use tensorflow's built-in function, tf.function()

In [51]:
tf.add(tensor, 100)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 117],
       [113, 114]], dtype=int32)>

**Matrix Multiplication**

In machine learning, tensor multipliccation is one of the most common tensor operations

There are two rules our tensors (or matrices) need to fufill if we are going to matrix multiply them

1. The inner dimension must match
2. The resulting matrix has the shape of outer dimensions

(Inner dimensions: are the number of columns of the first matrix and the number of rows of the second matrix, and they must match)

In [52]:
# Matrix Multiplication in tensorflow
tensor = tf.constant([[10,7], [3,4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [53]:
# This operation become element wise (not matrix multiplication)
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [54]:
# Matrix multiplication with python operator "@"

In [55]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
tensor_1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_2 = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [57]:
# Create a (3,2) tensor
X = tf.constant([[1,2],
         [3,4],
         [5,6]])
# Create another (3,2) tensor
Y = tf.constant([[7,8],
         [9,10],
         [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [58]:
# Try to matrix m7ultiplication with tensors of same shape
# tf.matmul(X, Y)   # Matrix size-incompatible

In [59]:
X.shape, tf.reshape(Y, shape = (2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [60]:
# Let's change the shape of y
Y, tf.reshape(Y, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [61]:
# Try to multiply X by reshaped Y
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
# Try change the shape of X instead of Y
tf.reshape(X, shape = (2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [63]:
tf.matmul(tf.reshape(X, shape = (2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

# the effect of transpose is different from reshape
# transpose change the column and row
# reshape do not change the relative position of the element

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [65]:
# Try matrix multiplication with tranpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Resource: info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

**The dot product**

Matrix multiplication is also referred to as the dot product

You can perform matrix multiplication using:
* tf.matmul(): https://www.tensorflow.org/api_docs/python/tf/linalg/matmul
* tf.tensordot(): https://www.tensorflow.org/api_docs/python/tf/tensordot

In [66]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [67]:
# Perform matrix multiplication on X and Y (require X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [68]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [69]:
# Perform martix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [70]:
# Check the value of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")
print("Reshaped Y:")
print(tf.reshape(Y, shape = (2,3)), "\n")
print("Transposed Y:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes is not lined up, you willl transpose rather than reshape one of the tensors to satisfy matrix multiplication rules

### Change the datatype of a tensor

**tf.cast(tensor, dtype = dtype))**

**resources**: https://www.tensorflow.org/api_docs/python/tf/tensordot

In [71]:
tf.__version__

'2.18.0'

In [72]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [73]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [74]:
# Change from float32 to float16 (reduced precision with less memory, run faster)
D = tf.cast(B, dtype = tf.float16)
D.dtype, B.dtype

(tf.float16, tf.float32)

In [75]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E.dtype

tf.float32

In [76]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16.dtype

tf.float16

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [77]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [78]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go throgh the folowing form of aggregaiton
* Get the minimun
* Get the maximum
* Get the mean of a tensor
* Get the sum of the tensor


In [79]:
# Find the mean of tensor (dtype = int32)
D, tf.reduce_mean(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-8>)

In [80]:
# Find the mean of tensor (dtype = float32)
D = tf.cast(D, dtype = tf.float32)
D, tf.reduce_mean(D)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -7., -10.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-8.5>)

In [81]:
# Find the min and max and sum of tensor
tf.reduce_min(D), tf.reduce_max(D), tf.reduce_sum(D)

(<tf.Tensor: shape=(), dtype=float32, numpy=-10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-7.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-17.0>)

In [82]:
# Create another random tensor between 0 and 100 with size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 57, 71, 49,  4, 99, 45, 12, 11,  3, 82, 30, 35, 14, 92, 99, 71,
       86, 12, 34, 47,  6, 28, 90, 52, 71, 38, 79, 26, 55, 87, 11, 43, 38,
       14, 73, 48, 40, 42, 75, 10, 42, 15, 27, 65, 51, 57, 23, 40,  7])>

In [83]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [84]:
# Find min, max, sum, mean,
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_sum(E), tf.reduce_mean(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=3>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2238>,
 <tf.Tensor: shape=(), dtype=int64, numpy=44>)

**Excercise: finding variance and std_dev using tensorflow method**

In [85]:
# Find the std
# tf.math.reduce_std(E) # TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.
E = tf.cast(E, dtype = tf.float32)
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=27.50895118713379>

The input tensor must be complex type or float to be used in .math.reduce_std()

In [86]:
# Find the variance
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=756.742431640625>

In [87]:
# Another method using tensorflow_probability library
import tensorflow_probability as tfp

tfp.stats.variance(D)

<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

### Find the positional maximun and minimun

resource: https://www.tensorflow.org/api_docs/python/tf/math/argmax

In [88]:
# Creating a new tensor for findng the positional maximun and minimun
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [89]:
# Find the positional maximun
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

F[...]: This is the standard indexing operation.

It takes the index found in step 1 and uses it to retrieve the actual value at that position in tensor F

In [90]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [91]:
# Index on our largest value position
F[tf.argmax((F))]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [92]:
# Chec for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [93]:
# Find the positional minimun (index) and use the index to dinf the value of the positional minimu
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>)

In [94]:
# Practice
mytensor = [1,2,3,4,5,6]
tf.argmax(mytensor), mytensor[tf.argmax(mytensor)], tf.argmin(mytensor), mytensor[tf.argmin(mytensor)]

(<tf.Tensor: shape=(), dtype=int64, numpy=5>,
 6,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 1)

### Squeezing a tensor (removing all single dimensions)

In [95]:
# Creare a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [96]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [97]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [98]:
# Create a list of indices
some_list = [0,1,2,3] # red, green, blue, purple

# One hot encode pur list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [99]:
# Specify custome value for one-hot encoding
tf.one_hot(some_list, depth = 4, on_value = "Yes", off_value = "no")
# depth: A scalar defining the depth of the one hot dimension.

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'no', b'no', b'no'],
       [b'no', b'Yes', b'no', b'no'],
       [b'no', b'no', b'Yes', b'no'],
       [b'no', b'no', b'no', b'Yes']], dtype=object)>

The depth argument specifies the total number of possible categories, which in turn defines the length of each one-hot vector.


resource: https://www.tensorflow.org/api_docs/python/tf/one_hot

### Squaring, log, sqaure root

In [100]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

resource: https://www.tensorflow.org/api_docs/python/tf/range

In [101]:
# square a tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [102]:
# Find the square root
# tf.math.sqrt(H)   # Value for attr 'T' of int32 is not in the list of allowed values: Method requires non-int type
H = tf.cast(H, dtype = tf.float32)
tf.math.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [103]:
# Find the log, also int is not allowed input
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interact beutifully with numpy arrays

**Note:** One of the main difference between a Tensorflow tensor and a numpy array is that the Tensorflow tensor can be run on a GPU or TPU for faster numerical processing

In [104]:
# Create a tensor directly form a numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [105]:
# Conver out tensor into a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [106]:
# Convert tensor J into a Numpy array
J.numpy(), type(J.numpy)

(array([ 3.,  7., 10.]), method)

In [107]:
# The default type of each is slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

When we want to convert a numpy array to a tensor, the datatype will be different from where we directly create a tensor

### Finding access to GPUs
https://www.tensorflow.org/api_docs/python/tf/config/list_physical_devices

```
# 此內容會顯示為程式碼
```



In [108]:
tf.config.list_physical_devices(), tf.config.list_physical_devices("GPU")

([PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')], [])

**Note:**

If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible

### Excercise 1 (Fundamental)


In [109]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
myscaler = tf.constant(7)
mymatrix = tf.constant([2,3])
mytensor = tf.constant([[2,3],[4,5]])

In [110]:
# 2. Find the shape, rank and size of the tensors you created in 1.
def describe_tensor(tensor):
  print(tensor.shape)
  print(tensor.ndim)
  print(tf.size(tensor))
  print("-"*50)

describe_tensor(myscaler), describe_tensor(mymatrix), describe_tensor(mytensor)

()
0
tf.Tensor(1, shape=(), dtype=int32)
--------------------------------------------------
(2,)
1
tf.Tensor(2, shape=(), dtype=int32)
--------------------------------------------------
(2, 2)
2
tf.Tensor(4, shape=(), dtype=int32)
--------------------------------------------------


(None, None, None)

In [111]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor_1 = tf.random.uniform(shape = [5,300])
tensor_2 = tf.random.uniform(shape = [5,300])
tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

In [112]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tensor_1.shape, tensor_2.shape        # (TensorShape([5, 300]), TensorShape([5, 300]))
tf.matmul(tensor_1, tf.transpose(tensor_2))  # (5X300)(300X5) = (5X5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.714005, 80.87824 , 78.32848 , 78.259705, 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.277405],
       [75.16    , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.113556, 75.401215, 72.79378 , 75.066376, 75.206535],
       [79.87284 , 83.40138 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [113]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor_3 = tf.random.uniform(shape = [224, 224, 3])

In [114]:
# 7. Find the min and max values of the tensor you created in 6.
tf.reduce_min(tensor_3), tf.reduce_max(tensor_3)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.0967254638671875e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999902248382568>)

In [115]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
tensor_4 = tf.random.uniform(shape = [1, 224, 224, 3])
tensor_4_squeezed = tf.squeeze(tensor_4)
tensor_4.shape, tensor_4_squeezed.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [116]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_5 = [1,2,3,4,5,6,7,8,9,10]
tf.argmax(tensor_5), tensor_5[tf.argmax(tensor_5)]

(<tf.Tensor: shape=(), dtype=int64, numpy=9>, 10)

In [117]:
# 10. One-hot encode the tensor you created in 9.
tf.one_hot(tensor_5, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [118]:
tensor_6 = [0,1,2,3,4,5,6,7,8,9]
tf.one_hot(tensor_6, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

### Excercise 2 (Fundamental)

In [119]:
# 1. Tensor Creation: Create the following tensors using tf.constant()
# A scalar with the value 42.
# A vector with the values [2, 4, 6, 8].
# A matrix with the values [[1, 1], [2, 2]].:

myscaler = tf.constant(42)
myvector = tf.constant([2,4,6,8])
mymatrix = tf.constant([[1, 1], [2, 2]])

myscaler, myvector, mymatrix

(<tf.Tensor: shape=(), dtype=int32, numpy=42>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2]], dtype=int32)>)

In [120]:
# 2. Tensor Properties: For the matrix you created in question 1, use TensorFlow attributes to find the following:
# Its shape.
# Its rank (number of dimensions).
# Its total number of elements (size).

def describe_tensor(tensor):
  print(f"tensor shape :{tensor.shape}")
  print(f"tensor rank: {tensor.ndim}")
  print(f"tensor size: {tf.size(tensor)}")
  print("-"*50)

describe_tensor(myscaler), describe_tensor(myvector), describe_tensor(mymatrix)

tensor shape :()
tensor rank: 0
tensor size: 1
--------------------------------------------------
tensor shape :(4,)
tensor rank: 1
tensor size: 4
--------------------------------------------------
tensor shape :(2, 2)
tensor rank: 2
tensor size: 4
--------------------------------------------------


(None, None, None)

In [121]:
# 3. Random Tensors and Reproducibility:
# Create two identical random tensors with a shape of (3, 2).
# The values should be drawn from a normal distribution. How do you ensure they are identical?

random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape = (3,2))
random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape = (3,2))

random_tensor_1, random_tensor_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [122]:
# 4. Matrix Multiplication: You have two tensors:
# Tensor A with shape (3, 4).
# Tensor B with shape (3, 4).
# Both contain random values.
# Can you perform matrix multiplication on them as they are?
# If not, what do you need to do to multiply them, and what will be the shape of the resulting tensor? Perform the multiplication.

random_tensor_3 = tf.random.Generator.from_seed(42)
random_tensor_3 = random_tensor_3.normal(shape = (3,4))
random_tensor_4 = tf.random.Generator.from_seed(5)
random_tensor_4 = random_tensor_4.normal(shape = (3,4))
random_tensor_3, random_tensor_4

tensor_5 = tf.matmul(random_tensor_3, tf.transpose(random_tensor_4))
tensor_5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-3.1179538 , -0.3399103 ,  1.0268608 ],
       [-1.6873126 ,  1.7158719 , -0.25646275],
       [-1.3675727 , -0.17333645,  0.72422135]], dtype=float32)>

In [139]:
# 5. Data Type Conversion and Aggregation:
# Create a tensor with integer values: tf.constant([1, 5, 10, -3, 8]).
# Calculate the standard deviation and variance of this tensor. What do you need to do to the tensor's data type before you can perform these calculations?

tensor = tf.constant([1, 5, 10, -3, 8])
tensor = tf.cast(tensor, dtype = tf.float32)

tf.math.reduce_variance(tensor), tf.math.reduce_std(tensor),

(<tf.Tensor: shape=(), dtype=float32, numpy=22.15999984741211>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.7074408531188965>)

In [138]:
# 6. Indexing to Find Extrema:
# Create a random tensor of shape [20] with values between 0 and 1.
# Find the index (position) of the maximum value in this tensor.
# Use the found index to retrieve the maximum value from the tensor.

tf.random.set_seed(42)
tensor = tf.random.uniform(shape = [20])
max_index = tf.argmax(tensor)              # return the index of the positional maximun

tensor[max_index], tensor                # use the index to retrieve the maximun value

(<tf.Tensor: shape=(), dtype=float32, numpy=0.8996834754943848>,
 <tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
       dtype=float32)>)

In [137]:
# 7. Manipulating Tensor Shapes:
# Create a tensor with the shape (1, 1, 5, 1).
# Use tf.squeeze() to remove the dimensions of size 1. What is the new shape of the tensor?

tf.random.set_seed(42)
tensor = tf.random.Generator.from_seed(42)
tensor = tensor.uniform(shape = (1, 1, 5, 1))

tensor, tf.squeeze(tensor)

(<tf.Tensor: shape=(1, 1, 5, 1), dtype=float32, numpy=
 array([[[[0.7493447 ],
          [0.73561966],
          [0.45230794],
          [0.49039817],
          [0.1889317 ]]]], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ],
       dtype=float32)>)

In [142]:
# 8. One-Hot Encoding:
# You have a list of indices representing different categories: [0, 2, 1, 3, 0].
# Assume there are 4 unique categories in total. One-hot encode this list of indices.

mylist = [0, 2, 1, 3, 0]
tf.one_hot(mylist, depth = 4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]], dtype=float32)>

In [155]:
# 9. Basic Mathematical Operations:
# Create a tensor H using tf.range(1, 11).
# Perform the following operations on H:
# Find the natural logarithm (log).
# Find the square root.
# What must you do to tensor H before you can perform these operations?

tensor = tf.range(1,11)
tensor   # dtype=int32

# need type casting before using log and sqrt finction
tf.math.log(tf.cast(tensor, tf.float32)), tf.math.sqrt(tf.cast(tensor, tf.float32))

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246, 2.3025851], dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
        2.6457512, 2.828427 , 3.       , 3.1622777], dtype=float32)>)

In [159]:
# 10. Tensors and NumPy:
# Create a NumPy array with the values [3.0, 5.0, 7.0].
# Convert this NumPy array into a TensorFlow tensor.
# What is the default data type of the resulting tensor when created from a NumPy array with floating-point numbers? How does it differ from a tensor created directly using tf.constant([3.0, 5.0, 7.0])?

myarray = np.array([3.0, 5.0, 7.0])
tensor_1 = tf.constant(myarray)
tensor_2 = tf.constant([3.0, 5.0, 7.0])

tensor_1, tensor_2

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 7.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 5., 7.], dtype=float32)>)

### Excercise 3 (Advanced)

In [190]:
# 1. Data Pipeline Simulation
# Create a tensor A with the shape (3, 5) containing random integer values between 0 and 50.
# Create a second tensor B with the shape (3, 5) containing random floating-point values between 0 and 1.
# Perform the following operation: (A * 5) + B. What must you do to tensor A's data type for this operation to work?
# Finally, find the sum of all elements in the resulting tensor.

tensor_1 = tf.random.uniform(minval = 0, maxval = 50, shape = (3, 5), dtype = tf.int32)
tensor_2 = tf.random.uniform(minval = 0, maxval = 50, shape = (3, 5), dtype = tf.float32)

tensor_3 = tf.cast(tensor_1, dtype = tf.float32)*5 + tensor_2
tf.reduce_sum(tensor_3)

<tf.Tensor: shape=(), dtype=float32, numpy=2152.98193359375>

1. tf.random.uniform: This is a simple, direct function. It's the most common way to create a single random tensor.

- tensor = tf.random.uniform(shape=(2, 2), minval=0, maxval=10, dtype=tf.int32, seed=42)

2. tf.random.Generator: This creates an object that manages its own internal state for random number generation. It is useful in more complex situations where you need to pass a specific source of randomness to different parts of your program.

- Create a generator object with a seed
g = tf.random.Generator.from_seed(42)

- Use the object to create a random tensor
tensor_1 = g.uniform(shape=(2, 2), minval=0, maxval=10, dtype=tf.int32)

- Use it again to get the next random tensor in the sequence
tensor_2 = g.uniform(shape=(2, 2), minval=0, maxval=10, dtype=tf.int32)

In [256]:
# 2. Matrix Multiplication and Broadcasting
# Create a tensor X of shape (4, 3) with random values.
# Create a vector v of shape (3,) with random values.
# Can you multiply X by v using tf.matmul? If not, what must you do to v to make the shapes compatible for matrix multiplication?
# Perform the multiplication. What is the shape of the resulting tensor?

X = tf.random.uniform(shape = (4,3))
v = tf.random.uniform(shape = (3,))
v = tf.reshape(v, shape = (3,1))

tf.matmul(X, v)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.6328528 ],
       [0.8895362 ],
       [1.1871238 ],
       [0.67850834]], dtype=float32)>

use tf.reshape() on vector v to satisfy the rule of matrix multiplication

In [205]:
# 3. Reproducible Shuffling and Aggregation
# Create a tensor containing the integers from 0 to 14, and reshape it into a (3, 5) matrix.
# Set the global random seed to 42.
# Shuffle this tensor so that the rows are in a new, random order, but the values within each row remain the same.
# From this shuffled tensor, find the mean of the values in each column.

tf.random.set_seed(42)
tensor = tf.random.uniform(minval = 0, maxval = 14, shape = (3,5))
tensor_shuffled = tf.random.shuffle(tensor)

tensor, tensor_shuffled

(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[ 9.303869  ,  6.174095  ,  4.9403553 ,  6.5027556 ,  0.47124577],
        [ 9.585413  , 10.361644  , 12.214223  ,  3.1685688 ,  3.124756  ],
        [ 4.345433  , 10.112701  ,  1.8646204 ,  7.6728945 ,  8.044523  ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[ 4.345433  , 10.112701  ,  1.8646204 ,  7.6728945 ,  8.044523  ],
        [ 9.303869  ,  6.174095  ,  4.9403553 ,  6.5027556 ,  0.47124577],
        [ 9.585413  , 10.361644  , 12.214223  ,  3.1685688 ,  3.124756  ]],
       dtype=float32)>)

In [238]:
# 4. Finding and Masking the Maximum Value
# Create a random tensor of shape (5, 5).
# Find the position (index) of the single largest value in the entire flattened tensor.
# Create a new tensor of the same (5, 5) shape that is all zeros, except for a 1.0 at the position of the maximum value you found.
# Hint: You might need to combine tf.argmax, tf.one_hot, and tf.reshape

tf.random.set_seed(42)
tensor = tf.random.uniform(shape = (5,5))
tensor_reshaped = tf.reshape(tensor, shape = (25))   # flatten the tensor
tf.argmax(tensor_reshaped)                  # index of the positional maximun of the flattened tensor

mylist = list(0 for i in range(25))
mylist[tf.argmax(tensor_reshaped)] = 1           # mylist = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

tf.convert_to_tensor(mylist)
tf.reshape(mylist, shape = (5,5))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [239]:
# alternative for practice 4
# Flatten the tensor and find the index of the max value
flat_tensor = tf.reshape(tensor, [-1]) # -1 is a shortcut to flatten
max_index = tf.argmax(flat_tensor)

# Use tf.one_hot to create the flat mask
# The depth must be the total number of elements (25)
mask_flat = tf.one_hot(max_index, depth=25)

# Reshape the flat mask to the final (5, 5) shape
mask = tf.reshape(mask_flat, (5, 5))

print(mask)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)


**Note**

Breaking Down tf.one_hot(indices, depth)
The function needs two main inputs:

- indices: This is the position you want to turn "on". In this case, it's the index of the maximum value you found with tf.argmax. So, indices would be 17.**(The output of tf.one_hot will have one more dimension than the input indices tensor.)**

- depth: This tells the function how long the final vector should be (how many "switches" are on the control panel). Since your flattened tensor has 25 elements, you need a vector of length 25 to represent all possible positions. Therefore, depth=25

In [252]:
# 5. Transpose vs. Reshape for Dot Product
# Create a tensor M with shape (2, 3) using values from tf.range(6).
# Create a second tensor N with the same shape (2, 3) using values from tf.range(start=6, limit=12).
# Calculate the dot product of M and N. To do this, you will need to modify the shape of N.
# Perform the dot product twice:
# First, by using tf.transpose() on N.
# Second, by using tf.reshape() on N.
# Print both results. Are they the same? Briefly explain why or why not, based on your notebook's explanation of transpose and reshape.

M = tf.range(6)
N = tf.range(start=6, limit=12)

M_1 = tf.reshape(M, shape = (2,3))
N_1 = tf.reshape(N, shape = (2,3))

product_reshaped = tf.matmul(M_1, tf.reshape(N_1, shape = (3,2)))
product_transposed = tf.matmul(M_1, tf.transpose(N_1))

product_reshaped, product_transposed

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 28,  31],
        [100, 112]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 23,  32],
        [ 86, 122]], dtype=int32)>)

### List of TensorFlow Python APIs - Pick one we haven't gone through in this notebook


**tf.concat**

In [161]:
tensor_1 = tf.constant([[1,2,3],
             [4,5,6]])
tensor_2 = tf.constant([[7,8,9],
             [10,11,12]])
tensor_3 = tf.concat([tensor_1, tensor_2], axis = 0)    # concat at axix = 0
tensor_4 = tf.concat([tensor_1, tensor_2], axis = 1)    # concat at axix = 1
tensor_3, tensor_4

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]], dtype=int32)>)

**tf.convert_to_tensor**


In [162]:
mylist = [1,2,3,4]
tf.convert_to_tensor(mylist)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [163]:
mytuple = (1,2,3,4)
tf.convert_to_tensor(mytuple)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [164]:
# create a function to convert python list or python tuple to a tensor with specified datatype
def convert_to_tensor_function(arg):
  tensor = tf.convert_to_tensor(arg, dtype = tf.float32)
  return tensor

convert_to_tensor_function([1,2,3,4]), convert_to_tensor_function((1,2,3,4))

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>)